#!/usr/bin/env node
/**
 * Deterministically turns public/icons/*.svg into React components.
 * The source SVGs remain canonical; never edit src/icons by hand.
 */
import { mkdir, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { relative, resolve } from "node:path";

const packageDirectory = resolve(import.meta.dirname, "..");
const repositoryDirectory = resolve(packageDirectory, "..", "..");
const svgDirectory = resolve(repositoryDirectory, "public", "icons");
const outputDirectory = resolve(packageDirectory, "src", "icons");
const checkOnly = process.argv.includes("--check");

const reactAttributeNames = {
  "accept-charset": "acceptCharset",
  "class": "className",
  "clip-path": "clipPath",
  "clip-rule": "clipRule",
  "fill-opacity": "fillOpacity",
  "fill-rule": "fillRule",
  "font-family": "fontFamily",
  "font-size": "fontSize",
  "gradient-transform": "gradientTransform",
  "gradient-units": "gradientUnits",
  "stop-color": "stopColor",
  "stop-opacity": "stopOpacity",
  "stroke-linecap": "strokeLinecap",
  "stroke-linejoin": "strokeLinejoin",
  "stroke-miterlimit": "strokeMiterlimit",
  "stroke-opacity": "strokeOpacity",
  "stroke-width": "strokeWidth",
  "tabindex": "tabIndex",
  "xlink:href": "xlinkHref",
  "xmlns:xlink": "xmlnsXlink",
};

const correctedNames = new Map([
  ["tiket", "Ticket"],
  ["multy-person", "MultiPerson"],
  ["unfold-colse", "UnfoldClose"],
]);

function pascalCase(name) {
  return name
    .split("-")
    .filter(Boolean)
    .map((part) => (/^\d/.test(part) ? part : part[0].toUpperCase() + part.slice(1)))
    .join("");
}

function componentName(name) {
  return pascalCase(name);
}

function correctedComponentName(name) {
  for (const [wrong, correct] of correctedNames) {
    if (name === wrong || name.startsWith(`${wrong}-`)) {
      return `${correct}${pascalCase(name.slice(wrong.length))}`;
    }
  }
  return null;
}

function jsxAttribute(name, value) {
  const reactName = reactAttributeNames[name] ?? name;
  if (reactName === "id") return `id={\`${"${idPrefix}"}-${value}\`}`;
  if (value.includes("url(#")) {
    const expression = value.replaceAll(/url\(#([^)]+)\)/g, "url(#${idPrefix}-$1)");
    return `${reactName}={\`${expression}\`}`;
  }
  if ((reactName === "href" || reactName === "xlinkHref") && value.startsWith("#")) {
    return `${reactName}={\`#${"${idPrefix}"}-${value.slice(1)}\`}`;
  }
  return `${reactName}=${JSON.stringify(value)}`;
}

function svgToJsx(svg, name) {
  const root = svg.match(/<svg\b([^>]*)>([\s\S]*?)<\/svg>\s*$/i);
  if (!root) throw new Error(`${name}: expected one root <svg> element`);

  const rootAttributes = Object.fromEntries(
    [...root[1].matchAll(/([:\w-]+)=(?:"([^"]*)"|'([^']*)')/g)].map((match) => [match[1], match[2] ?? match[3] ?? ""]),
  );
  const viewBox = rootAttributes.viewBox ?? "0 0 24 24";
  const preserveColor = name.endsWith("-color") || /<(?:linear|radial)Gradient\b|url\(#/i.test(svg);
  let body = root[2].replace(/<!--[\s\S]*?-->/g, "");

  if (!preserveColor) {
    body = body.replace(/\b(fill|stroke)=("|')(?:#18181b|#000000|#000|black)\2/gi, "$1=\"currentColor\"");
  }

  body = body.replace(/([:\w-]+)=("[^"]*"|'[^']*')/g, (attribute, rawName, quotedValue) => {
    const value = quotedValue.slice(1, -1);
    return jsxAttribute(rawName, value);
  });

  return { jsx: body.trim(), viewBox, isColor: preserveColor };
}

function iconModule(icon) {
  return `// Generated by scripts/generate-icons.mjs from public/icons/${icon.file}. Do not edit.\n` +
    `import * as React from "react";\n` +
    `import { createIconComponent } from "../create-icon-component.js";\n\n` +
    `export const ${icon.component} = createIconComponent("${icon.component}", ${JSON.stringify(icon.viewBox)}, (idPrefix) => (\n` +
    `  <>\n${icon.jsx.split("\n").map((line) => `    ${line}`).join("\n")}\n  </>\n` +
    `));\n`;
}

function registryModule(icons) {
  const imports = icons.map((icon) => `import { ${icon.component} } from "./icons/${icon.name}.js";`).join("\n");
  const componentExports = icons.map((icon) => icon.component).join(", ");
  const records = icons.map((icon) => `  "${icon.name}": ${icon.component},`).join("\n");
  const metadata = icons
    .map(
      (icon) => `  { name: "${icon.name}", componentName: "${icon.component}", viewBox: "${icon.viewBox}", isColor: ${icon.isColor} },`)
    .join("\n");
  const dynamicImports = icons
    .map((icon) => `  "${icon.name}": () => import("./icons/${icon.name}.js"),`)
    .join("\n");
  const aliases = icons
    .filter((icon) => icon.correctedComponent)
    .map(
      (icon) =>
        `/** @deprecated Use ${icon.correctedComponent}; this name preserves the source filename spelling. */\nexport { ${icon.component} };\nexport const ${icon.correctedComponent} = ${icon.component};`,
    )
    .join("\n\n");
  const regularExports = icons.filter((icon) => !icon.correctedComponent).map((icon) => icon.component).join(", ");

  return `// Generated by scripts/generate-icons.mjs. Do not edit.\n` +
    `import type { IconMetadata, MinimIconComponent } from "./types.js";\n${imports}\n\n` +
    `export { ${regularExports} };\n\n${aliases}\n\n` +
    `export const iconNames = [\n${icons.map((icon) => `  "${icon.name}",`).join("\n")}\n] as const;\n\n` +
    `export type IconName = (typeof iconNames)[number];\n\n` +
    `export const icons: readonly IconMetadata[] = [\n${metadata}\n];\n\n` +
    `export const iconComponents: Record<IconName, MinimIconComponent> = {\n${records}\n};\n\n` +
    `/** Lazily load a single generated component by its source icon name. */\n` +
    `export const dynamicIconImports: Record<IconName, () => Promise<Record<string, MinimIconComponent>>> = {\n${dynamicImports}\n};\n`;
}

async function writeGenerated(path, contents) {
  if (checkOnly) {
    try {
      if ((await readFile(path, "utf8")) !== contents) throw new Error("outdated");
    } catch {
      throw new Error(`Generated file is out of date: ${relative(repositoryDirectory, path)}. Run npm run react:generate.`);
    }
    return;
  }
  await writeFile(path, contents);
}

const sourceFiles = (await readdir(svgDirectory)).filter((file) => file.endsWith(".svg")).sort();
const icons = await Promise.all(
  sourceFiles.map(async (file) => {
    const name = file.slice(0, -4);
    const converted = svgToJsx(await readFile(resolve(svgDirectory, file), "utf8"), name);
    return {
      file,
      name,
      component: componentName(name),
      correctedComponent: correctedComponentName(name),
      ...converted,
    };
  }),
);

if (!checkOnly) {
  await rm(outputDirectory, { recursive: true, force: true });
  await mkdir(outputDirectory, { recursive: true });
}

for (const icon of icons) await writeGenerated(resolve(outputDirectory, `${icon.name}.tsx`), iconModule(icon));
await writeGenerated(resolve(packageDirectory, "src", "icons.ts"), registryModule(icons));
console.log(`${checkOnly ? "Verified" : "Generated"} ${icons.length} React icons from public/icons.`);
