// Generated by scripts/generate-icons.mjs from public/icons/align-down-outline.svg. Do not edit.
import * as React from "react";
import { createIconComponent } from "../create-icon-component.js";

export const AlignDownOutline = createIconComponent("AlignDownOutline", "0 0 24 24", (idPrefix) => (
  <>
    <path d="M11.2499 5C11.2499 4.58579 11.5857 4.25 11.9999 4.25C12.4142 4.25 12.7499 4.58579 12.7499 5V17.1895L15.4697 14.4697C15.7626 14.1768 16.2373 14.1768 16.5302 14.4697C16.8231 14.7626 16.8231 15.2374 16.5302 15.5303L12.5302 19.5303C12.3896 19.6709 12.1989 19.75 11.9999 19.75C11.801 19.75 11.6103 19.6709 11.4697 19.5303L7.46967 15.5303C7.17678 15.2374 7.17678 14.7626 7.46967 14.4697C7.76256 14.1768 8.23732 14.1768 8.53022 14.4697L11.2499 17.1895V5Z" fill="currentColor"/>
  </>
));
