// Generated by scripts/generate-icons.mjs from public/icons/arrow-left-outline.svg. Do not edit.
import * as React from "react";
import { createIconComponent } from "../create-icon-component.js";

export const ArrowLeftOutline = createIconComponent("ArrowLeftOutline", "0 0 24 24", (idPrefix) => (
  <>
    <path d="M10.4697 4.46967C10.7626 4.17678 11.2373 4.17678 11.5302 4.46967C11.8231 4.76256 11.8231 5.23732 11.5302 5.53022L5.81049 11.2499H19.9999C20.4142 11.2499 20.7499 11.5857 20.7499 11.9999C20.7499 12.4142 20.4142 12.7499 19.9999 12.7499H5.81049L11.5302 18.4697C11.8231 18.7626 11.8231 19.2373 11.5302 19.5302C11.2373 19.8231 10.7626 19.8231 10.4697 19.5302L3.46967 12.5302C3.17678 12.2373 3.17678 11.7626 3.46967 11.4697L10.4697 4.46967Z" fill="currentColor"/>
  </>
));
