// Generated by scripts/generate-icons.mjs from public/icons/arrow-up-solid.svg. Do not edit.
import * as React from "react";
import { createIconComponent } from "../create-icon-component.js";

export const ArrowUpSolid = createIconComponent("ArrowUpSolid", "0 0 24 24", (idPrefix) => (
  <>
    <path d="M10.9999 20V6.41407L5.70696 11.707C5.31643 12.0976 4.68342 12.0976 4.29289 11.707C3.90237 11.3165 3.90237 10.6835 4.29289 10.293L11.2929 3.29298L11.3691 3.22462C11.7618 2.90427 12.3408 2.92686 12.707 3.29298L19.707 10.293C20.0975 10.6835 20.0975 11.3165 19.707 11.707C19.3164 12.0976 18.6834 12.0976 18.2929 11.707L12.9999 6.41407V20C12.9999 20.5523 12.5522 21 11.9999 21C11.4476 21 10.9999 20.5523 10.9999 20Z" fill="currentColor"/>
  </>
));
