// Generated by scripts/generate-icons.mjs from public/icons/arrow-right-outline.svg. Do not edit.
import * as React from "react";
import { createIconComponent } from "../create-icon-component.js";

export const ArrowRightOutline = createIconComponent("ArrowRightOutline", "0 0 24 24", (idPrefix) => (
  <>
    <path d="M12.4697 4.46967C12.7626 4.17678 13.2374 4.17678 13.5303 4.46967L20.5303 11.4697C20.8232 11.7626 20.8232 12.2373 20.5303 12.5302L13.5303 19.5302C13.2374 19.8231 12.7626 19.8231 12.4697 19.5302C12.1768 19.2373 12.1768 18.7626 12.4697 18.4697L18.1895 12.7499H4C3.58579 12.7499 3.25 12.4142 3.25 11.9999C3.25 11.5857 3.58579 11.2499 4 11.2499H18.1895L12.4697 5.53022C12.1768 5.23732 12.1768 4.76256 12.4697 4.46967Z" fill="currentColor"/>
  </>
));
