// Generated by scripts/generate-icons.mjs from public/icons/arrow-up-left-outline.svg. Do not edit.
import * as React from "react";
import { createIconComponent } from "../create-icon-component.js";

export const ArrowUpLeftOutline = createIconComponent("ArrowUpLeftOutline", "0 0 24 24", (idPrefix) => (
  <>
    <path d="M5.25 16V6C5.25 5.58579 5.58579 5.25 6 5.25H16C16.4142 5.25 16.75 5.58579 16.75 6C16.75 6.41421 16.4142 6.75 16 6.75H7.81055L18.5303 17.4697C18.8232 17.7626 18.8232 18.2374 18.5303 18.5303C18.2374 18.8232 17.7626 18.8232 17.4697 18.5303L6.75 7.81055V16C6.75 16.4142 6.41421 16.75 6 16.75C5.58579 16.75 5.25 16.4142 5.25 16Z" fill="currentColor"/>
  </>
));
