// Generated by scripts/generate-icons.mjs from public/icons/arrow-down-right-outline.svg. Do not edit.
import * as React from "react";
import { createIconComponent } from "../create-icon-component.js";

export const ArrowDownRightOutline = createIconComponent("ArrowDownRightOutline", "0 0 24 24", (idPrefix) => (
  <>
    <path d="M5.46967 5.46967C5.76256 5.17678 6.23732 5.17678 6.53022 5.46967L17.2499 16.1894V7.99994C17.2499 7.58573 17.5857 7.24994 17.9999 7.24994C18.4142 7.24994 18.7499 7.58573 18.7499 7.99994V17.9999C18.7499 18.1989 18.6709 18.3896 18.5302 18.5302C18.3896 18.6709 18.1989 18.7499 17.9999 18.7499H7.99994C7.58573 18.7499 7.24994 18.4142 7.24994 17.9999C7.24994 17.5857 7.58573 17.2499 7.99994 17.2499H16.1894L5.46967 6.53022C5.17678 6.23732 5.17678 5.76256 5.46967 5.46967Z" fill="currentColor"/>
  </>
));
