// Generated by scripts/generate-icons.mjs from public/icons/arrow-start-left-solid.svg. Do not edit.
import * as React from "react";
import { createIconComponent } from "../create-icon-component.js";

export const ArrowStartLeftSolid = createIconComponent("ArrowStartLeftSolid", "0 0 24 24", (idPrefix) => (
  <>
    <path d="M20 4C20.5523 4 21 4.44772 21 5V19C21 19.5523 20.5523 20 20 20C19.4477 20 19 19.5523 19 19V5C19 4.44772 19.4477 4 20 4Z" fill="currentColor"/>
    <path d="M7.29297 7.29297C7.68349 6.90244 8.31651 6.90244 8.70703 7.29297C9.09752 7.6835 9.09754 8.31652 8.70703 8.70703L6.41406 11H16C16.5523 11 17 11.4477 17 12C17 12.5522 16.5523 13 16 13H6.41406L8.70703 15.293C9.09752 15.6835 9.09754 16.3165 8.70703 16.707C8.31652 17.0975 7.68348 17.0975 7.29297 16.707L3.29297 12.707C3.10545 12.5195 3.00002 12.2652 3 12C3 11.7348 3.10546 11.4805 3.29297 11.293L7.29297 7.29297Z" fill="currentColor"/>
  </>
));
