// Generated by scripts/generate-icons.mjs from public/icons/arrow-down-solid.svg. Do not edit.
import * as React from "react";
import { createIconComponent } from "../create-icon-component.js";

export const ArrowDownSolid = createIconComponent("ArrowDownSolid", "0 0 24 24", (idPrefix) => (
  <>
    <path d="M10.9999 4C10.9999 3.44772 11.4476 3 11.9999 3C12.5522 3 12.9999 3.44772 12.9999 4V17.5859L18.2929 12.293C18.6834 11.9024 19.3164 11.9024 19.707 12.293C20.0975 12.6835 20.0975 13.3165 19.707 13.707L12.707 20.707C12.5194 20.8946 12.2651 21 11.9999 21C11.7347 21 11.4804 20.8946 11.2929 20.707L4.29289 13.707C3.90237 13.3165 3.90237 12.6835 4.29289 12.293C4.68342 11.9024 5.31643 11.9024 5.70696 12.293L10.9999 17.5859V4Z" fill="currentColor"/>
  </>
));
