// Generated by scripts/generate-icons.mjs from public/icons/arrow-down-right-solid.svg. Do not edit.
import * as React from "react";
import { createIconComponent } from "../create-icon-component.js";

export const ArrowDownRightSolid = createIconComponent("ArrowDownRightSolid", "0 0 24 24", (idPrefix) => (
  <>
    <path d="M5.29302 5.29302C5.68354 4.90249 6.31655 4.90249 6.70708 5.29302L17 15.586V8.00005C17 7.44776 17.4478 7.00005 18 7.00005C18.5523 7.00005 19 7.44776 19 8.00005V18C19 18.2653 18.8946 18.5195 18.7071 18.7071C18.5195 18.8946 18.2653 19 18 19H8.00005C7.44776 19 7.00005 18.5523 7.00005 18C7.00005 17.4478 7.44776 17 8.00005 17H15.586L5.29302 6.70708C4.90249 6.31655 4.90249 5.68354 5.29302 5.29302Z" fill="currentColor"/>
  </>
));
