// Generated by scripts/generate-icons.mjs from public/icons/arrow-up-right-solid.svg. Do not edit.
import * as React from "react";
import { createIconComponent } from "../create-icon-component.js";

export const ArrowUpRightSolid = createIconComponent("ArrowUpRightSolid", "0 0 24 24", (idPrefix) => (
  <>
    <path d="M19 16C19 16.5523 18.5523 17 18 17C17.4478 17 17 16.5523 17 16V8.41406L6.70708 18.707C6.31655 19.0976 5.68354 19.0976 5.29302 18.707C4.90249 18.3165 4.90249 17.6835 5.29302 17.293L15.586 7H8.00005C7.44776 7 7.00005 6.55228 7.00005 6C7.00005 5.44772 7.44776 5 8.00005 5H18C18.5523 5 19 5.44772 19 6V16Z" fill="currentColor"/>
  </>
));
