// Generated by scripts/generate-icons.mjs from public/icons/arrow-right-solid.svg. Do not edit.
import * as React from "react";
import { createIconComponent } from "../create-icon-component.js";

export const ArrowRightSolid = createIconComponent("ArrowRightSolid", "0 0 24 24", (idPrefix) => (
  <>
    <path d="M12.293 4.29302C12.6835 3.90249 13.3165 3.90249 13.707 4.29302L20.707 11.293C21.0976 11.6835 21.0976 12.3166 20.707 12.7071L13.707 19.7071C13.3165 20.0976 12.6835 20.0976 12.293 19.7071C11.9024 19.3166 11.9024 18.6835 12.293 18.293L17.5859 13H4C3.44772 13 3 12.5523 3 12C3 11.4478 3.44772 11 4 11H17.5859L12.293 5.70708C11.9024 5.31655 11.9024 4.68354 12.293 4.29302Z" fill="currentColor"/>
  </>
));
