// Generated by scripts/generate-icons.mjs from public/icons/arrow-up-left-solid.svg. Do not edit.
import * as React from "react";
import { createIconComponent } from "../create-icon-component.js";

export const ArrowUpLeftSolid = createIconComponent("ArrowUpLeftSolid", "0 0 24 24", (idPrefix) => (
  <>
    <path d="M5 16V6C5 5.44772 5.44772 5 6 5H16C16.5523 5 17 5.44772 17 6C17 6.55228 16.5523 7 16 7H8.41406L18.707 17.293C19.0976 17.6835 19.0976 18.3165 18.707 18.707C18.3165 19.0976 17.6835 19.0976 17.293 18.707L7 8.41406V16C7 16.5523 6.55228 17 6 17C5.44772 17 5 16.5523 5 16Z" fill="currentColor"/>
  </>
));
