// Generated by scripts/generate-icons.mjs from public/icons/arrow-start-right-solid.svg. Do not edit.
import * as React from "react";
import { createIconComponent } from "../create-icon-component.js";

export const ArrowStartRightSolid = createIconComponent("ArrowStartRightSolid", "0 0 24 24", (idPrefix) => (
  <>
    <path d="M4 4C4.55228 4 5 4.44772 5 5V19C5 19.5523 4.55228 20 4 20C3.44772 20 3 19.5523 3 19V5C3 4.44772 3.44772 4 4 4Z" fill="currentColor"/>
    <path d="M15.293 7.29297C15.6835 6.90244 16.3165 6.90244 16.707 7.29297L20.707 11.293C21.0975 11.6835 21.0975 12.3165 20.707 12.707L16.707 16.707C16.3165 17.0975 15.6835 17.0975 15.293 16.707C14.9025 16.3165 14.9025 15.6835 15.293 15.293L17.5859 13H8C7.44774 13 7.00004 12.5522 7 12C7 11.4477 7.44772 11 8 11H17.5859L15.293 8.70703C14.9025 8.31652 14.9025 7.6835 15.293 7.29297Z" fill="currentColor"/>
  </>
));
