// Generated by scripts/generate-icons.mjs from public/icons/chat-solid.svg. Do not edit.
import * as React from "react";
import { createIconComponent } from "../create-icon-component.js";

export const ChatSolid = createIconComponent("ChatSolid", "0 0 24 24", (idPrefix) => (
  <>
    <path d="M12 2C17.5228 2 22 6.47715 22 12C22 17.5228 17.5228 22 12 22C10.3696 22 8.82862 21.6078 7.4668 20.9141L4.85938 21.5654C3.39461 21.9316 2.06838 20.6054 2.43457 19.1406L3.08594 16.5332C2.39216 15.1714 2 13.6304 2 12C2 6.47715 6.47715 2 12 2Z" fill="currentColor"/>
  </>
));
