// Generated by scripts/generate-icons.mjs from public/icons/checkbox-mixed-outline.svg. Do not edit.
import * as React from "react";
import { createIconComponent } from "../create-icon-component.js";

export const CheckboxMixedOutline = createIconComponent("CheckboxMixedOutline", "0 0 24 24", (idPrefix) => (
  <>
    <path d="M16 11.25C16.4142 11.25 16.75 11.5858 16.75 12C16.75 12.4142 16.4142 12.75 16 12.75H8C7.58579 12.75 7.25 12.4142 7.25 12C7.25 11.5858 7.58579 11.25 8 11.25H16Z" fill="currentColor"/>
    <path fillRule="evenodd" clipRule="evenodd" d="M17 3.25C19.0711 3.25 20.75 4.92893 20.75 7V17C20.75 19.0711 19.0711 20.75 17 20.75H7C4.92893 20.75 3.25 19.0711 3.25 17V7C3.25 4.92893 4.92893 3.25 7 3.25H17ZM7 4.75C5.75736 4.75 4.75 5.75736 4.75 7V17C4.75 18.2426 5.75736 19.25 7 19.25H17C18.2426 19.25 19.25 18.2426 19.25 17V7C19.25 5.75736 18.2426 4.75 17 4.75H7Z" fill="currentColor"/>
  </>
));
