// Generated by scripts/generate-icons.mjs from public/icons/checkbox-solid.svg. Do not edit.
import * as React from "react";
import { createIconComponent } from "../create-icon-component.js";

export const CheckboxSolid = createIconComponent("CheckboxSolid", "0 0 24 24", (idPrefix) => (
  <>
    <path fillRule="evenodd" clipRule="evenodd" d="M17 3C19.2091 3 21 4.79086 21 7V17C21 19.2091 19.2091 21 17 21H7C4.79086 21 3 19.2091 3 17V7C3 4.79086 4.79086 3 7 3H17Z" fill="currentColor"/>
  </>
));
