// Generated by scripts/generate-icons.mjs from public/icons/chevron-down-solid.svg. Do not edit.
import * as React from "react";
import { createIconComponent } from "../create-icon-component.js";

export const ChevronDownSolid = createIconComponent("ChevronDownSolid", "0 0 24 24", (idPrefix) => (
  <>
    <path d="M18.2929 8.29302C18.6834 7.90249 19.3164 7.90249 19.707 8.29302C20.0975 8.68354 20.0975 9.31655 19.707 9.70708L12.707 16.7071C12.3164 17.0976 11.6834 17.0976 11.2929 16.7071L4.29289 9.70708C3.90237 9.31655 3.90237 8.68354 4.29289 8.29302C4.68342 7.90249 5.31643 7.90249 5.70696 8.29302L11.9999 14.586L18.2929 8.29302Z" fill="currentColor"/>
  </>
));
