// Generated by scripts/generate-icons.mjs from public/icons/chevron-left-solid.svg. Do not edit.
import * as React from "react";
import { createIconComponent } from "../create-icon-component.js";

export const ChevronLeftSolid = createIconComponent("ChevronLeftSolid", "0 0 24 24", (idPrefix) => (
  <>
    <path d="M14.2929 4.29302C14.6834 3.90249 15.3164 3.90249 15.707 4.29302C16.0975 4.68354 16.0975 5.31655 15.707 5.70708L9.41399 12L15.707 18.293C16.0975 18.6835 16.0975 19.3166 15.707 19.7071C15.3164 20.0976 14.6834 20.0976 14.2929 19.7071L7.29289 12.7071C6.90237 12.3166 6.90237 11.6835 7.29289 11.293L14.2929 4.29302Z" fill="currentColor"/>
  </>
));
