// Generated by scripts/generate-icons.mjs from public/icons/chevron-down-outline.svg. Do not edit.
import * as React from "react";
import { createIconComponent } from "../create-icon-component.js";

export const ChevronDownOutline = createIconComponent("ChevronDownOutline", "0 0 24 24", (idPrefix) => (
  <>
    <path d="M18.4697 8.46967C18.7626 8.17678 19.2373 8.17678 19.5302 8.46967C19.8231 8.76256 19.8231 9.23732 19.5302 9.53022L12.5302 16.5302C12.2373 16.8231 11.7626 16.8231 11.4697 16.5302L4.46967 9.53022C4.17678 9.23732 4.17678 8.76256 4.46967 8.46967C4.76256 8.17678 5.23732 8.17678 5.53022 8.46967L11.9999 14.9394L18.4697 8.46967Z" fill="currentColor"/>
  </>
));
