// Generated by scripts/generate-icons.mjs from public/icons/chevron-right-solid.svg. Do not edit.
import * as React from "react";
import { createIconComponent } from "../create-icon-component.js";

export const ChevronRightSolid = createIconComponent("ChevronRightSolid", "0 0 24 24", (idPrefix) => (
  <>
    <path d="M8.29289 4.29302C8.68342 3.90249 9.31643 3.90249 9.70696 4.29302L16.707 11.293C17.0975 11.6835 17.0975 12.3166 16.707 12.7071L9.70696 19.7071C9.31643 20.0976 8.68342 20.0976 8.29289 19.7071C7.90237 19.3166 7.90237 18.6835 8.29289 18.293L14.5859 12L8.29289 5.70708C7.90237 5.31655 7.90237 4.68354 8.29289 4.29302Z" fill="currentColor"/>
  </>
));
