// Generated by scripts/generate-icons.mjs from public/icons/chevron-right-tight-outline.svg. Do not edit.
import * as React from "react";
import { createIconComponent } from "../create-icon-component.js";

export const ChevronRightTightOutline = createIconComponent("ChevronRightTightOutline", "0 0 18 24", (idPrefix) => (
  <>
    <path d="M5.46967 4.46967C5.76256 4.17678 6.23732 4.17678 6.53022 4.46967L13.5302 11.4697C13.8231 11.7626 13.8231 12.2373 13.5302 12.5302L6.53022 19.5302C6.23732 19.8231 5.76256 19.8231 5.46967 19.5302C5.17678 19.2373 5.17678 18.7626 5.46967 18.4697L11.9394 11.9999L5.46967 5.53022C5.17678 5.23732 5.17678 4.76256 5.46967 4.46967Z" fill="currentColor"/>
  </>
));
