// Generated by scripts/generate-icons.mjs from public/icons/chevron-up-outline.svg. Do not edit.
import * as React from "react";
import { createIconComponent } from "../create-icon-component.js";

export const ChevronUpOutline = createIconComponent("ChevronUpOutline", "0 0 24 24", (idPrefix) => (
  <>
    <path d="M11.5263 7.41796C11.8209 7.17765 12.2556 7.19512 12.5302 7.46972L19.5302 14.4697C19.8231 14.7626 19.8231 15.2374 19.5302 15.5303C19.2373 15.8232 18.7626 15.8232 18.4697 15.5303L11.9999 9.06054L5.53022 15.5303C5.23732 15.8232 4.76256 15.8232 4.46967 15.5303C4.17678 15.2374 4.17678 14.7626 4.46967 14.4697L11.4697 7.46972L11.5263 7.41796Z" fill="currentColor"/>
  </>
));
