// Generated by scripts/generate-icons.mjs from public/icons/chevron-left-outline.svg. Do not edit.
import * as React from "react";
import { createIconComponent } from "../create-icon-component.js";

export const ChevronLeftOutline = createIconComponent("ChevronLeftOutline", "0 0 24 24", (idPrefix) => (
  <>
    <path d="M14.4697 4.46967C14.7626 4.17678 15.2373 4.17678 15.5302 4.46967C15.8231 4.76256 15.8231 5.23732 15.5302 5.53022L9.06049 11.9999L15.5302 18.4697C15.8231 18.7626 15.8231 19.2373 15.5302 19.5302C15.2373 19.8231 14.7626 19.8231 14.4697 19.5302L7.46967 12.5302C7.17678 12.2373 7.17678 11.7626 7.46967 11.4697L14.4697 4.46967Z" fill="currentColor"/>
  </>
));
