// Generated by scripts/generate-icons.mjs from public/icons/chevron-right-outline.svg. Do not edit.
import * as React from "react";
import { createIconComponent } from "../create-icon-component.js";

export const ChevronRightOutline = createIconComponent("ChevronRightOutline", "0 0 24 24", (idPrefix) => (
  <>
    <path d="M8.46967 4.46967C8.76256 4.17678 9.23732 4.17678 9.53022 4.46967L16.5302 11.4697C16.8231 11.7626 16.8231 12.2373 16.5302 12.5302L9.53022 19.5302C9.23732 19.8231 8.76256 19.8231 8.46967 19.5302C8.17678 19.2373 8.17678 18.7626 8.46967 18.4697L14.9394 11.9999L8.46967 5.53022C8.17678 5.23732 8.17678 4.76256 8.46967 4.46967Z" fill="currentColor"/>
  </>
));
