// Generated by scripts/generate-icons.mjs from public/icons/copy-solid.svg. Do not edit.
import * as React from "react";
import { createIconComponent } from "../create-icon-component.js";

export const CopySolid = createIconComponent("CopySolid", "0 0 24 24", (idPrefix) => (
  <>
    <path fillRule="evenodd" clipRule="evenodd" d="M14 2C16.2091 2 18 3.79086 18 6C20.2091 6 22 7.79086 22 10V18C22 20.2091 20.2091 22 18 22H10C7.79086 22 6 20.2091 6 18C3.79086 18 2 16.2091 2 14V6C2 3.79086 3.79086 2 6 2H14ZM18 14C18 16.2091 16.2091 18 14 18H8C8 19.1046 8.89543 20 10 20H18C19.1046 20 20 19.1046 20 18V10C20 8.89543 19.1046 8 18 8V14Z" fill="currentColor"/>
  </>
));
