// Generated by scripts/generate-icons.mjs from public/icons/delete-solid.svg. Do not edit.
import * as React from "react";
import { createIconComponent } from "../create-icon-component.js";

export const DeleteSolid = createIconComponent("DeleteSolid", "0 0 24 24", (idPrefix) => (
  <>
    <path d="M15 2C15.5523 2 16 2.44772 16 3C16 3.55228 15.5523 4 15 4H9C8.44772 4 8 3.55228 8 3C8 2.44772 8.44772 2 9 2H15Z" fill="currentColor"/>
    <path fillRule="evenodd" clipRule="evenodd" d="M21 5C21.5523 5 22 5.44772 22 6C22 6.55228 21.5523 7 21 7H20V18C20 20.2091 18.2091 22 16 22H8C5.79086 22 4 20.2091 4 18V7H3C2.44772 7 2 6.55228 2 6C2 5.44772 2.44772 5 3 5H21ZM8.5 16V10C8.5 9.44772 8.94772 9 9.5 9C10.0523 9 10.5 9.44772 10.5 10V16C10.5 16.5523 10.0523 17 9.5 17C8.94772 17 8.5 16.5523 8.5 16ZM13.5 10V16C13.5 16.5523 13.9477 17 14.5 17C15.0523 17 15.5 16.5523 15.5 16V10C15.5 9.44772 15.0523 9 14.5 9C13.9477 9 13.5 9.44772 13.5 10Z" fill="currentColor"/>
  </>
));
