// Generated by scripts/generate-icons.mjs from public/icons/edit-solid.svg. Do not edit.
import * as React from "react";
import { createIconComponent } from "../create-icon-component.js";

export const EditSolid = createIconComponent("EditSolid", "0 0 24 24", (idPrefix) => (
  <>
    <path d="M18.0005 10.4141L7.70756 20.7071C7.57953 20.835 7.41833 20.9258 7.24272 20.9698L3.24272 21.9698C2.90217 22.0548 2.5418 21.9551 2.2935 21.7071C2.04523 21.4588 1.94582 21.0985 2.0308 20.7578L3.0308 16.7578L3.07182 16.6289C3.12192 16.5036 3.19743 16.3891 3.2935 16.293L13.5865 6.00003L18.0005 10.4141Z" fill="currentColor"/>
    <path d="M15.7935 3.79299C17.0125 2.57429 18.9887 2.57413 20.2076 3.79299C21.4261 5.01189 21.4262 6.98819 20.2076 8.20706L19.4146 9.00003L15.0005 4.58596L15.7935 3.79299Z" fill="currentColor"/>
  </>
));
