// Generated by scripts/generate-icons.mjs from public/icons/fast-forward-solid.svg. Do not edit.
import * as React from "react";
import { createIconComponent } from "../create-icon-component.js";

export const FastForwardSolid = createIconComponent("FastForwardSolid", "0 0 24 24", (idPrefix) => (
  <>
    <path d="M11 7.67021C11 5.74571 13.0833 4.54292 14.75 5.50517L22.25 9.83525C23.9166 10.7975 23.9166 13.2031 22.25 14.1653L14.75 18.4954C13.0834 19.4575 11.0001 18.2547 11 16.3304V15.4642L5.75 18.4954C4.0834 19.4575 2.00012 18.2547 2 16.3304V7.67021C2 5.74571 4.08333 4.54292 5.75 5.50517L11 8.53545V7.67021Z" fill="currentColor"/>
  </>
));
