// Generated by scripts/generate-icons.mjs from public/icons/fast-rewind-solid.svg. Do not edit.
import * as React from "react";
import { createIconComponent } from "../create-icon-component.js";

export const FastRewindSolid = createIconComponent("FastRewindSolid", "0 0 24 24", (idPrefix) => (
  <>
    <path d="M18.2501 5.50517C19.9167 4.54292 22.0001 5.74571 22.0001 7.67021V16.3304C21.9999 18.2547 19.9166 19.4575 18.2501 18.4954L13.0001 15.4642V16.3304C12.9999 18.2547 10.9166 19.4575 9.25007 18.4954L1.75007 14.1653C0.0834422 13.2031 0.083504 10.7975 1.75007 9.83525L9.25007 5.50517C10.9167 4.54292 13.0001 5.74571 13.0001 7.67021V8.53545L18.2501 5.50517Z" fill="currentColor"/>
  </>
));
