// Generated by scripts/generate-icons.mjs from public/icons/format-size-solid.svg. Do not edit.
import * as React from "react";
import { createIconComponent } from "../create-icon-component.js";

export const FormatSizeSolid = createIconComponent("FormatSizeSolid", "0 0 24 24", (idPrefix) => (
  <>
    <path d="M10 9C10.5523 9 11 9.44772 11 10C11 10.5523 10.5523 11 10 11H8V19C8 19.5523 7.55228 20 7 20C6.44772 20 6 19.5523 6 19V11H4C3.44772 11 3 10.5523 3 10C3 9.44772 3.44772 9 4 9H10Z" fill="currentColor"/>
    <path d="M20 4C20.5523 4 21 4.44772 21 5C21 5.55228 20.5523 6 20 6H16V19C16 19.5523 15.5523 20 15 20C14.4477 20 14 19.5523 14 19V6H10C9.44772 6 9 5.55228 9 5C9 4.44772 9.44772 4 10 4H20Z" fill="currentColor"/>
  </>
));
