// Generated by scripts/generate-icons.mjs from public/icons/format-align-center-solid.svg. Do not edit.
import * as React from "react";
import { createIconComponent } from "../create-icon-component.js";

export const FormatAlignCenterSolid = createIconComponent("FormatAlignCenterSolid", "0 0 24 24", (idPrefix) => (
  <>
    <path d="M16 17C16.5523 17 17 17.4477 17 18C17 18.5523 16.5523 19 16 19H8C7.44772 19 7 18.5523 7 18C7 17.4477 7.44772 17 8 17H16Z" fill="currentColor"/>
    <path d="M20 11C20.5523 11 21 11.4477 21 12C21 12.5523 20.5523 13 20 13H4C3.44772 13 3 12.5523 3 12C3 11.4477 3.44772 11 4 11H20Z" fill="currentColor"/>
    <path d="M18 5C18.5523 5 19 5.44772 19 6C19 6.55228 18.5523 7 18 7H6C5.44772 7 5 6.55228 5 6C5 5.44772 5.44772 5 6 5H18Z" fill="currentColor"/>
  </>
));
