// Generated by scripts/generate-icons.mjs from public/icons/format-title-outline.svg. Do not edit.
import * as React from "react";
import { createIconComponent } from "../create-icon-component.js";

export const FormatTitleOutline = createIconComponent("FormatTitleOutline", "0 0 24 24", (idPrefix) => (
  <>
    <path d="M18 4.25C18.4142 4.25 18.75 4.58579 18.75 5C18.75 5.41421 18.4142 5.75 18 5.75H12.75V19C12.75 19.4142 12.4142 19.75 12 19.75C11.5858 19.75 11.25 19.4142 11.25 19V5.75H6C5.58579 5.75 5.25 5.41421 5.25 5C5.25 4.58579 5.58579 4.25 6 4.25H18Z" fill="currentColor"/>
  </>
));
