// Generated by scripts/generate-icons.mjs from public/icons/format-title-solid.svg. Do not edit.
import * as React from "react";
import { createIconComponent } from "../create-icon-component.js";

export const FormatTitleSolid = createIconComponent("FormatTitleSolid", "0 0 24 24", (idPrefix) => (
  <>
    <path d="M18 4C18.5523 4 19 4.44772 19 5C19 5.55228 18.5523 6 18 6H13V19C13 19.5523 12.5523 20 12 20C11.4477 20 11 19.5523 11 19V6H6C5.44772 6 5 5.55228 5 5C5 4.44772 5.44772 4 6 4H18Z" fill="currentColor"/>
  </>
));
