// Generated by scripts/generate-icons.mjs from public/icons/format-align-right-solid.svg. Do not edit.
import * as React from "react";
import { createIconComponent } from "../create-icon-component.js";

export const FormatAlignRightSolid = createIconComponent("FormatAlignRightSolid", "0 0 24 24", (idPrefix) => (
  <>
    <path d="M20 17C20.5523 17 21 17.4477 21 18C21 18.5523 20.5523 19 20 19H12C11.4477 19 11 18.5523 11 18C11 17.4477 11.4477 17 12 17H20Z" fill="currentColor"/>
    <path d="M20 11C20.5523 11 21 11.4477 21 12C21 12.5523 20.5523 13 20 13H4C3.44772 13 3 12.5523 3 12C3 11.4477 3.44772 11 4 11H20Z" fill="currentColor"/>
    <path d="M20 5C20.5523 5 21 5.44772 21 6C21 6.55228 20.5523 7 20 7H8C7.44772 7 7 6.55228 7 6C7 5.44772 7.44772 5 8 5H20Z" fill="currentColor"/>
  </>
));
