// Generated by scripts/generate-icons.mjs from public/icons/format-underlined-solid.svg. Do not edit.
import * as React from "react";
import { createIconComponent } from "../create-icon-component.js";

export const FormatUnderlinedSolid = createIconComponent("FormatUnderlinedSolid", "0 0 24 24", (idPrefix) => (
  <>
    <path d="M19 18C19.5523 18 20 18.4477 20 19C20 19.5523 19.5523 20 19 20H5C4.44772 20 4 19.5523 4 19C4 18.4477 4.44772 18 5 18H19Z" fill="currentColor"/>
    <path d="M16 4C16.5523 4 17 4.44772 17 5V11C17 13.7614 14.7614 16 12 16C9.23858 16 7 13.7614 7 11V5C7 4.44772 7.44772 4 8 4C8.55228 4 9 4.44772 9 5V11C9 12.6569 10.3431 14 12 14C13.6569 14 15 12.6569 15 11V5C15 4.44772 15.4477 4 16 4Z" fill="currentColor"/>
  </>
));
