// Generated by scripts/generate-icons.mjs from public/icons/logo-kakao.svg. Do not edit.
import * as React from "react";
import { createIconComponent } from "../create-icon-component.js";

export const LogoKakao = createIconComponent("LogoKakao", "0 0 24 24", (idPrefix) => (
  <>
    <path d="M12 3C17.525 3 22 6.6 22 11.075C22 15.5 17.525 19.1 12 19.1C11.425 19.1 10.775 19.05 10.175 18.975L6.15 21.775C6.1 21.775 6.05 21.825 5.95 21.825C5.9 21.825 5.825 21.775 5.775 21.775C5.675 21.65 5.65 21.525 5.675 21.425L6.65 17.85C3.85 16.425 2 13.9 2 11.075C2 6.6 6.475 3 12 3Z" fill="currentColor"/>
  </>
));
