// Generated by scripts/generate-icons.mjs from public/icons/logo-naver.svg. Do not edit.
import * as React from "react";
import { createIconComponent } from "../create-icon-component.js";

export const LogoNaver = createIconComponent("LogoNaver", "0 0 24 24", (idPrefix) => (
  <>
    <g id={`${idPrefix}-logo-naver`}>
    <path id={`${idPrefix}-icon`} d="M14.725 4V12.05L9.27495 4H3.44995V20H9.27495V11.925L14.725 20H20.575V4H14.725Z" fill="currentColor"/>
    </g>
  </>
));
