// Generated by scripts/generate-icons.mjs from public/icons/minus-solid.svg. Do not edit.
import * as React from "react";
import { createIconComponent } from "../create-icon-component.js";

export const MinusSolid = createIconComponent("MinusSolid", "0 0 24 24", (idPrefix) => (
  <>
    <path d="M4 13H11H20C20.5523 13 21 12.5523 21 12C21 11.4477 20.5523 11 20 11H11H4C3.44772 11 3 11.4477 3 12C3 12.5523 3.44772 13 4 13Z" fill="currentColor"/>
  </>
));
