// Generated by scripts/generate-icons.mjs from public/icons/pause-outline.svg. Do not edit.
import * as React from "react";
import { createIconComponent } from "../create-icon-component.js";

export const PauseOutline = createIconComponent("PauseOutline", "0 0 24 24", (idPrefix) => (
  <>
    <path fillRule="evenodd" clipRule="evenodd" d="M8 4.25C9.51878 4.25 10.75 5.48122 10.75 7V17C10.75 18.5188 9.51878 19.75 8 19.75C6.48122 19.75 5.25 18.5188 5.25 17V7C5.25 5.48122 6.48122 4.25 8 4.25ZM8 5.75C7.30964 5.75 6.75 6.30964 6.75 7V17C6.75 17.6904 7.30964 18.25 8 18.25C8.69036 18.25 9.25 17.6904 9.25 17V7C9.25 6.30964 8.69036 5.75 8 5.75Z" fill="currentColor"/>
    <path fillRule="evenodd" clipRule="evenodd" d="M16 4.25C17.5188 4.25 18.75 5.48122 18.75 7V17C18.75 18.5188 17.5188 19.75 16 19.75C14.4812 19.75 13.25 18.5188 13.25 17V7C13.25 5.48122 14.4812 4.25 16 4.25ZM16 5.75C15.3096 5.75 14.75 6.30964 14.75 7V17C14.75 17.6904 15.3096 18.25 16 18.25C16.6904 18.25 17.25 17.6904 17.25 17V7C17.25 6.30964 16.6904 5.75 16 5.75Z" fill="currentColor"/>
  </>
));
