// Generated by scripts/generate-icons.mjs from public/icons/pause-solid.svg. Do not edit.
import * as React from "react";
import { createIconComponent } from "../create-icon-component.js";

export const PauseSolid = createIconComponent("PauseSolid", "0 0 24 24", (idPrefix) => (
  <>
    <path d="M8 4C9.65685 4 11 5.34315 11 7V17C11 18.6569 9.65685 20 8 20C6.34315 20 5 18.6569 5 17V7C5 5.34315 6.34315 4 8 4Z" fill="currentColor"/>
    <path d="M16 4C17.6569 4 19 5.34315 19 7V17C19 18.6569 17.6569 20 16 20C14.3431 20 13 18.6569 13 17V7C13 5.34315 14.3431 4 16 4Z" fill="currentColor"/>
  </>
));
