// Generated by scripts/generate-icons.mjs from public/icons/play-outline.svg. Do not edit.
import * as React from "react";
import { createIconComponent } from "../create-icon-component.js";

export const PlayOutline = createIconComponent("PlayOutline", "0 0 24 24", (idPrefix) => (
  <>
    <path d="M19.1249 10.0519C20.6247 10.9179 20.6247 13.0823 19.1249 13.9484L8.62489 20.0109C7.12498 20.8768 5.25012 19.7945 5.24989 18.0626V5.93761C5.25012 4.20575 7.12498 3.1234 8.62489 3.98937L19.1249 10.0519ZM18.3749 12.6495C18.8748 12.3608 18.8748 11.6394 18.3749 11.3507L7.87489 5.2882C7.375 4.99967 6.75012 5.36048 6.74989 5.93761V18.0626C6.75012 18.6397 7.375 19.0005 7.87489 18.712L18.3749 12.6495Z" fill="currentColor"/>
  </>
));
