// Generated by scripts/generate-icons.mjs from public/icons/play-solid.svg. Do not edit.
import * as React from "react";
import { createIconComponent } from "../create-icon-component.js";

export const PlaySolid = createIconComponent("PlaySolid", "0 0 24 24", (idPrefix) => (
  <>
    <path d="M5 5.93792C5.00023 4.01366 7.08345 2.81082 8.75 3.77289L19.25 9.83539C20.9165 10.7977 20.9166 13.2032 19.25 14.1655L8.75 20.228C7.08358 21.1898 5.0005 19.9869 5 18.0629V5.93792Z" fill="currentColor"/>
  </>
));
