// Generated by scripts/generate-icons.mjs from public/icons/plus-outline.svg. Do not edit.
import * as React from "react";
import { createIconComponent } from "../create-icon-component.js";

export const PlusOutline = createIconComponent("PlusOutline", "0 0 24 24", (idPrefix) => (
  <>
    <path d="M11.25 20V12.75H4C3.58579 12.75 3.25 12.4142 3.25 12C3.25 11.5858 3.58579 11.25 4 11.25H11.25V4C11.25 3.58579 11.5858 3.25 12 3.25C12.4142 3.25 12.75 3.58579 12.75 4V11.25H20C20.4142 11.25 20.75 11.5858 20.75 12C20.75 12.4142 20.4142 12.75 20 12.75H12.75V20C12.75 20.4142 12.4142 20.75 12 20.75C11.5858 20.75 11.25 20.4142 11.25 20Z" fill="currentColor"/>
  </>
));
