// Generated by scripts/generate-icons.mjs from public/icons/radio-checked-solid.svg. Do not edit.
import * as React from "react";
import { createIconComponent } from "../create-icon-component.js";

export const RadioCheckedSolid = createIconComponent("RadioCheckedSolid", "0 0 24 24", (idPrefix) => (
  <>
    <path d="M12 7C14.7614 7 17 9.23858 17 12C17 14.7614 14.7614 17 12 17C9.23858 17 7 14.7614 7 12C7 9.23858 9.23858 7 12 7Z" fill="currentColor"/>
    <path fillRule="evenodd" clipRule="evenodd" d="M12 2C17.5228 2 22 6.47715 22 12C22 17.5228 17.5228 22 12 22C6.47715 22 2 17.5228 2 12C2 6.47715 6.47715 2 12 2ZM12 4C7.58172 4 4 7.58172 4 12C4 16.4183 7.58172 20 12 20C16.4183 20 20 16.4183 20 12C20 7.58172 16.4183 4 12 4Z" fill="currentColor"/>
  </>
));
