// Generated by scripts/generate-icons.mjs from public/icons/search-outline.svg. Do not edit.
import * as React from "react";
import { createIconComponent } from "../create-icon-component.js";

export const SearchOutline = createIconComponent("SearchOutline", "0 0 24 24", (idPrefix) => (
  <>
    <path fillRule="evenodd" clipRule="evenodd" d="M11 2.75C15.5563 2.75 19.25 6.44365 19.25 11C19.25 13.0081 18.5314 14.8477 17.3389 16.2783L20.5303 19.4697C20.8231 19.7626 20.8231 20.2374 20.5303 20.5303C20.2374 20.8231 19.7626 20.8231 19.4697 20.5303L16.2783 17.3389C14.8477 18.5314 13.0081 19.25 11 19.25C6.44365 19.25 2.75 15.5563 2.75 11C2.75 6.44365 6.44365 2.75 11 2.75ZM11 4.25C7.27208 4.25 4.25 7.27208 4.25 11C4.25 14.7279 7.27208 17.75 11 17.75C14.7279 17.75 17.75 14.7279 17.75 11C17.75 7.27208 14.7279 4.25 11 4.25Z" fill="currentColor"/>
  </>
));
