// Generated by scripts/generate-icons.mjs from public/icons/shopping-bag-solid.svg. Do not edit.
import * as React from "react";
import { createIconComponent } from "../create-icon-component.js";

export const ShoppingBagSolid = createIconComponent("ShoppingBagSolid", "0 0 24 24", (idPrefix) => (
  <>
    <path fillRule="evenodd" clipRule="evenodd" d="M12 2C14.2091 2 16 3.79086 16 6C18.2091 6 20 7.79086 20 10V18C20 20.2091 18.2091 22 16 22H8C5.79086 22 4 20.2091 4 18V10C4 7.79086 5.79086 6 8 6C8 3.79086 9.79086 2 12 2ZM12 4C10.8954 4 10 4.89543 10 6H14C14 4.89543 13.1046 4 12 4Z" fill="currentColor"/>
  </>
));
