// Generated by scripts/generate-icons.mjs from public/icons/skip-next-solid.svg. Do not edit.
import * as React from "react";
import { createIconComponent } from "../create-icon-component.js";

export const SkipNextSolid = createIconComponent("SkipNextSolid", "0 0 24 24", (idPrefix) => (
  <>
    <path d="M19 5C19.5523 5 20 5.44772 20 6V18C20 18.5523 19.5523 19 19 19C18.4477 19 18 18.5523 18 18V6C18 5.44772 18.4477 5 19 5Z" fill="currentColor"/>
    <path d="M4 7.66992C4.00003 5.74546 6.08335 4.54267 7.75 5.50488L15.25 9.83496C16.9167 10.7972 16.9166 13.2028 15.25 14.165L7.75 18.4951C6.08333 19.4574 4 18.2546 4 16.3301V7.66992Z" fill="currentColor"/>
  </>
));
