// Generated by scripts/generate-icons.mjs from public/icons/stop-outline.svg. Do not edit.
import * as React from "react";
import { createIconComponent } from "../create-icon-component.js";

export const StopOutline = createIconComponent("StopOutline", "0 0 24 24", (idPrefix) => (
  <>
    <path d="M18.25 9C18.25 7.20507 16.7949 5.75 15 5.75H9C7.20507 5.75 5.75 7.20507 5.75 9V15C5.75 16.7949 7.20507 18.25 9 18.25H15C16.7949 18.25 18.25 16.7949 18.25 15V9ZM19.75 15C19.75 17.6234 17.6234 19.75 15 19.75H9C6.37665 19.75 4.25 17.6234 4.25 15V9C4.25 6.37665 6.37665 4.25 9 4.25H15C17.6234 4.25 19.75 6.37665 19.75 9V15Z" fill="currentColor"/>
  </>
));
