// Generated by scripts/generate-icons.mjs from public/icons/stop-solid.svg. Do not edit.
import * as React from "react";
import { createIconComponent } from "../create-icon-component.js";

export const StopSolid = createIconComponent("StopSolid", "0 0 24 24", (idPrefix) => (
  <>
    <path d="M15 4C17.7614 4 20 6.23858 20 9V15C20 17.7614 17.7614 20 15 20H9C6.23858 20 4 17.7614 4 15V9C4 6.23858 6.23858 4 9 4H15Z" fill="currentColor"/>
  </>
));
